### ISSUE TITLE
Schemes do not appear

### ISSUE THREAD

**Issue by staff0rd** [tucali/ExampleAdapter#1]
I cloned this repo and gave it a shot, switching out the depenencies in the podfile for;

```
pod 'Google-Mobile-Ads-SDK', '~> 7.0'
pod 'FBAudienceNetwork', '~> 4.10.1'
```

After running `pod install` successfully, the resulting workspace still includes the old schemes, and does not include schemes for the dependencies above.  I attempted your instructions with a new project and found the same.  Additionally I tried `Autocreate Schemes Now` to no avail.

What am I missing?

Xcode 7.3
Cocoapods 1.1.0.rc.3

**Comment by taiheng** [comment]
Both these pods install a framework with no compiled code, use those directly in your project instead of through Cocoapods.
